### ISSUE TITLE
IP clearance for spring-boot project

### ISSUE THREAD

**Issue by ralf0131** [apache/dubbo-spring-boot-project#209]
Reference: https://issues.apache.org/jira/browse/DUBBO-3

**Comment by mercyblitz** [comment]
There are 2 branches:

#### 0.2.x   spring-boot 2.x support

* pom.xml has been updated with ASF info

Since this project is been actively developed and will expected
multiple release in the future. Here is what I suggest:

1. LICENSE/Disclaimer
2. change group id to org.apache
3. change package name to org.apache.dubbo

#### 0.1.x:  spring-boot 1.x support

* pom.xml has been updated with ASF info

Is this a maintenance branch? If there is a release, I think we need
to at least do:

1. LICENSE/Disclaimer
2. change group id to org.apache
