### ISSUE TITLE
[Enhancement] Add the default base package of Dubbo Service from Bootstrap class

### ISSUE THREAD

**Issue by mercyblitz** [apache/dubbo-spring-boot-project#519]
For now, the property `dubbo.scan.base-packages` is the only way to configure the base packages scanning the Dubbo service beans that annotated `@Service`. In order to simplify the configuration, it's required to add the default base package from bootstrap class.

**Comment by sunbufu** [comment]
In my opinion, when do not set `dubbo.scan.base-packages`, should use `@ComponentScan` specified basePackages and bootstrap class who annotated `@SpringBootApplication`. Can i send a PR for that?

**Comment by sunbufu** [comment]
Hello, I close my PR, because I realized I was wrong. We haven't decided on a definitive plan yet, but I've almost finished it. So, I think we should decide a solution about this issue, there are a few questions to help us.
  
1. Which packages should be default `base-packages` when `dubbo.scan.base-packages` is not set ?
> a. the packages with class annotated dubbo annotation. For example `@DubboComponentScan`, `@EnableDubbo` 
> b. the packages same as springBoot's packages
> c. the user's project root package

2. Which project should implement this ？
> a. dubbo
> b. dubbo-spring-boot-project
